version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:0.86.1
    volumes:
      - ./homeassistantconfig:/config
      - /etc/localtime:/etc/localtime:ro
      # - ./sslcert:/sslcert
    devices:
      - /dev/ttyACM1:/dev/ttyACM0
    restart: always
    network_mode: host
