version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:0.99.2
    volumes:
      - ./homeassistantconfig:/config
      - /etc/localtime:/etc/localtime:ro
      # - ./sslcert:/sslcert
    devices:
      - TTYDEVICE:/dev/ttyACM0
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
