- id: '1548503190225'
  alias: Termo ON 05:00
  trigger:
  - at: 05:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.switchone
    service: switch.turn_on
  - delay: 01:00
  - data:
      entity_id: switch.switchone
    service: switch.turn_off
- id: '1548515341571'
  alias: Enchufe baño
  trigger:
  - entity_id: switch.switchtwo
    for: 00:08:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.switchtwo
    service: switch.turn_off
  - delay: 00:00:30
  - data:
      entity_id: switch.switchtwo
    service: switch.turn_off
- id: termo_input_number
  alias: Termo slider Auto-Decrement
  trigger:
  - entity_id: input_number.termo_time
    platform: state
  action:
  - delay: 00:05:00
  - entity_id: input_number.termo_time
    service: input_number.decrement
- id: '1548527202535'
  alias: Termo Sensor OFF-ON
  trigger:
  - entity_id: binary_sensor.termo_on
    for: 00:00:10
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.switchone
    service: switch.turn_on
- id: '1548527264250'
  alias: Termo Sensor ON-OFF
  trigger:
  - entity_id: binary_sensor.termo_on
    for: 00:00:05
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.switchone
    service: switch.turn_off
- id: '1548531355158'
  alias: Termo más de hora y media encendido
  trigger:
  - entity_id: switch.switchone
    for: 01:30:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.switchone
    service: switch.turn_off
- id: '1548543806868'
  alias: Notificafion Puerta
  trigger:
  - entity_id: binary_sensor.maindoor
    for: 00:00:03
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.maindoor
    for: 00:00:03
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: "{% if is_state('binary_sensor.maindoor', 'on') %}\n     HOME => Puerta\
        \ abierta\n{% else %}\n     HOME => Puerta cerrada\n{% endif %} \n"
    service: notify.bot_to_grcanosa
