- id: '1548503190225'
  alias: Termo ON 05:00
  trigger:
  - at: 05:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.switch_termo
    service: switch.turn_on
  - delay: 01:00
  - data:
      entity_id: switch.switch_termo
    service: switch.turn_off
- id: '1548515341571'
  alias: Enchufe baño
  trigger:
  - entity_id: switch.switch_bano
    for: 00:08:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.switch_bano
    service: switch.turn_off
  - delay: 00:00:30
  - data:
      entity_id: switch.switch_bano
    service: switch.turn_off
- id: termo_input_number
  alias: Termo slider Auto-Decrement
  trigger:
  - entity_id: input_number.termo_time
    platform: state
  action:
  - data:
      entity_id: script.decrement_termo_time_in_5_min
    service: script.turn_off
  - delay: 00:00:05
  - data:
      entity_id: script.decrement_termo_time_in_5_min
    service: script.turn_on
- id: '1548531355158'
  alias: 'Termo: apagar si está más de hora y media encendido'
  trigger:
  - entity_id: switch.switch_termo
    for: 01:30:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.switch_termo
    service: switch.turn_off
  mode: single
- id: '1548543806868_2'
  alias: Notificafion Puerta
  trigger:
  - entity_id: binary_sensor.main_door
    for: 00:00:01
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.main_door
    for: 00:00:01
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: "{% if is_state('binary_sensor.main_door', 'on') %}\n     HOME => Puerta\
        \ abierta\n{% else %}\n     HOME => Puerta cerrada\n{% endif %} \n"
    service: notify.bot_to_grcanosa
  - data:
      message: "{% if is_state('binary_sensor.main_door', 'on') %}\n     HOME => Puerta\
        \ abierta\n{% else %}\n     HOME => Puerta cerrada\n{% endif %} \n"
    service: notify.bot_to_sara
- id: '1548797344389'
  alias: Switch Baño OFF each 30 min
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data:
      entity_id: switch.switch_bano
    service: switch.turn_off
- id: '1567972340401'
  alias: Termo ON 14.00
  trigger:
  - at: '14:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.switch_termo
    service: switch.turn_on
  - delay: 01:00
  - data:
      entity_id: switch.switch_termo
    service: switch.turn_off
- id: '1599999999999'
  alias: Cubo
  trigger:
  - entity_id: sensor.cubo_action
    platform: state
  action:
  - service: python_script.cubo
    data_template:
      full: '{{ trigger.to_state }}'
- id: '1569690957862'
  alias: Mensajes para Sara
  trigger:
  - entity_id: sensor.zigbee_button
    platform: state
    to: single
  - entity_id: sensor.zigbee_button
    platform: state
    to: double
  - entity_id: sensor.zigbee_button
    platform: state
    to: triple
  - entity_id: sensor.zigbee_button
    platform: state
    to: quadruple
  - entity_id: sensor.zigbee_button
    platform: state
    to: long_release
  condition: []
  action:
  - data_template:
      message: '{%if trigger.to_state.state == "single" %} ¡Guapa!  {% elif trigger.to_state.state
        == "double" %} ¡Te quiero! {% elif trigger.to_state.state == "triple" %} ¡Te
        quiero mucho! {% elif trigger.to_state.state == "quadruple" %} ¿Quieres tema?
        {% elif trigger.to_state.state == "long_release" %} Te quiero {{ trigger.to_state.attributes.duration
        }} millones. {% else %}{% endif %}'
    service: notify.bot_to_sara
- id: '1575486987531'
  alias: Luz Noche
  trigger:
  - at: '21:05'
    platform: time
  - event: sunset
    offset: 02:00
    platform: sun
  condition: []
  action:
  - device_id: 814253b9951d44c79944fef2bdd0c9aa
    domain: switch
    entity_id: switch.switch_bano
    type: turn_on
  - delay: '{{ (range(1,2)|random|int) }}:{{ (range(30, 59)|random|int) }}:00'
  - device_id: 814253b9951d44c79944fef2bdd0c9aa
    domain: switch
    entity_id: switch.switch_bano
    type: turn_off
- id: '1575487931483'
  alias: Apagar enchufe luz por la noche
  trigger:
  - at: 01:00
    platform: time
  condition: []
  action:
  - device_id: 814253b9951d44c79944fef2bdd0c9aa
    domain: switch
    entity_id: switch.switch_bano
    type: turn_off
- id: '1598532774319'
  alias: 'Termo: When slider changes, turn on and call timer'
  description: ''
  trigger:
  - entity_id: input_number.termo_time
    platform: state
  condition:
  - above: '0'
    condition: numeric_state
    entity_id: input_number.termo_time
  action:
  - data: {}
    entity_id: timer.termo
    service: timer.cancel
  - data: {}
    entity_id: switch.switch_termo
    service: switch.turn_on
  - data: {}
    entity_id: timer.termo
    service: timer.start
  mode: single
- id: '1598533503796'
  alias: 'Termo: Decrement slider when timer finishes'
  description: ''
  trigger:
  - event_data:
      entity_id: timer.termo
    event_type: timer.finished
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: input_number.termo_time
    service: input_number.decrement
  mode: single
- id: '1598533557732'
  alias: 'Termo: Off if slider gets to 0'
  description: ''
  trigger:
  - entity_id: input_number.termo_time
    for: 00:00:01
    platform: state
    to: '0.0'
  condition: []
  action:
  - data: {}
    entity_id: switch.switch_termo
    service: switch.turn_off
  - data: {}
    entity_id: timer.termo
    service: timer.cancel
  mode: single
