- id: '1548503190225'
  alias: Termo mañanas
  trigger:
  - at: 05:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.switchone
    service: switch.turn_on
  - delay: 01:00
  - data:
      entity_id: switch.switchone
    service: switch.turn_off
- id: '1548515341571'
  alias: Enchufe baño
  trigger:
  - entity_id: switch.switchtwo
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:10:00
  - data:
      entity_id: switch.switchtwo
    service: switch.turn_off
- id: 'termo_input_number'
  alias: Termo Manual
  trigger: 
    platform: state
      entity_id: input_number.termo_time
    action:
      - delay: '00:{{ states.input_number.termo_time.step | int }}:00'
      - service: "input_number.decrement"
        entity_id: "input_number.termo_time"