homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: 40.4165
  longitude: -3.7026
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml
  packages:
    zigbee2mqtt: !include zigbee2mqtt.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

lovelace:

transmission:
  host: 192.168.1.200
  username: !secret transmission_username
  password: !secret transmission_password
  monitored_conditions:
    - download_speed
    - upload_speed
    - active_torrents
    - total_torrents

speedtestdotnet:

#device_tracker:
#  - platform: nmap_tracker
#    hosts:
#      - 192.168.1.0/24

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

recorder:
  purge_keep_days: 3
  purge_interval: 1
  
logger:
  default: info

# Track the sun
# sun:

# Sensors
sensor:
  - platform: time_date
    display_options:
      - 'date'
      - 'time'
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw
  # Weather prediction
  # - platform: yr

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

weblink:
  entities:
    - name: Router
      url: http://192.168.1.1
    - name: Mongo
      url: http://192.168.1.200:7776
    - name: Transmission
      url: http://192.168.1.200:9091
    


zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
#  network_key: "0x2e, 0xcc, 0xab, 0x0b, 0xa3, 0x0a, 0x0e, 0xb5, 0x70, 0x71, 0x2d, 0xb4, 0x25, 0x43, 0xee, 0x0c"

telegram_bot:
  - platform: broadcast
    api_key: !secret grcanosabot_apikey
    allowed_chat_ids:
      - !secret grcanosa_chatid
      - !secret sara_chatid

notify:
  - name: bot_to_grcanosa
    platform: telegram
    chat_id: !secret grcanosa_chatid
  - name: bot_to_sara
    platform: telegram
    chat_id: !secret sara_chatid

#xiaomi_aqara:
#  discovery_retry: 10
#  interface: 192.168.1.201
#  gateways:
#    - key: !secret xiaomikey
#      host: 192.168.1.199
#      mac: !secret xiaomimac

mqtt:
  discovery: true
  broker: localhost  # Remove if you want to use builtin-in MQTT broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


input_number:
  termo_time:
    name: Minutos termo
    icon: mdi:clock-start
    initial: 0
    min: 0
    max: 75
    step: 5
    unit_of_measurement: min



binary_sensor:
  - platform: template
    sensors:
      termo_on:
        friendly_name: "Termo should be ON"
        value_template: >-
          {{ states.input_number.termo_time.state | int > 0 }}