sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_9:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_10:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_11:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_12:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_9:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_10:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_11:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_12:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_power_management_5:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_8:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_7:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_6:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_5:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_8:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_7:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_6:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_5:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_exporting_4:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_alarm_type_3:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_power_management_4:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_alarm_level_4:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_alarm_type_4:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_exporting_5:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_sourcenodeid_5:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_alarm_level_3:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_sourcenodeid_4:
  ignored: true
  polling_intensity: 0
