sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_3:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_4:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_interval:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_interval_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_interval_3:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_interval_4:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_previous_reading_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_previous_reading_3:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_previous_reading_4:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_interval:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_interval_2:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_interval_3:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_interval_4:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_power_management:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_power_management:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_exporting:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_power_plug_12a_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_unknown_type_0200_id_1027_exporting:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_access_control:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_sourcenodeid:
  ignored: true
  polling_intensity: 0
