sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_9:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_10:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_11:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_interval_12:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_9:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_10:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_11:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_previous_reading_12:
  ignored: true
  polling_intensity: 0
sensor.shenzhen_neo_electronics_co_ltd_power_plug_12a_power_management_5:
  ignored: true
  polling_intensity: 0
